name: hipocapp
description: "The official HipocApp Flutter project."


publish_to: 'none'
version: 1.0.1+21


environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  #Core
  icons_launcher: ^3.0.0
  flutter_native_splash: ^2.4.7
  equatable: ^2.0.7
  get_it: ^9.1.0
  intl: ^0.20.2
  
  #Widgets
  toggle_switch: ^2.3.0
  introduction_screen: ^4.0.0
  shimmer: ^3.0.0
  
  url_launcher: ^6.3.1
  buttons_tabbar: ^1.3.14
  awesome_snackbar_content: ^0.1.8
  material_floating_search_bar_plus: ^1.0.1


  #Config
  easy_localization: ^3.0.7
  
  #Network
  vexana: ^5.0.3
  signalr_netcore: ^1.4.3
  
  #State
  flutter_bloc: ^9.0.0

  #Utility
  kartal: ^4.2.0
  easy_logger: ^0.0.2
  logger: ^2.5.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  flutter_hooks: ^0.21.2
  encrypt: ^5.0.3

  #Animated Text
  animated_text_kit: ^4.2.3

  #Navigation
  auto_route: ^10.2.2

  widgets:
    path: module/widgets
  
  gen:
    path: module/gen
  
  common: 
    path: module/common

  core:
    path: module/core

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.0.0
  auto_route_generator: ^10.2.6
  build_runner: ^2.10.4
  


flutter:
  uses-material-design: true

  assets:
    - asset/translations/
    - asset/images/